### ISSUE TITLE
occassionally get buffer exists error

### ISSUE THREAD

**Issue by davidosomething** [AndrewRadev/bufferize.vim#1]
multiple runs of `:Bufferize messages`
yields:

```
Error detected while processing function bufferize#Run:
line   34:
E95: Buffer with this name already exists
```

**Comment by AndrewRadev** [comment]
Hm, interesting. I think this is caused by running the `file` command on a separate buffer, but I can't seem to be able to reproduce it. Are you running `:Bufferize messages` one after the other, or are you maybe closing the first one and opening a new one? Either one seems to work fine for me, I'm just looking for more information on the process that reproduces the problem.

Either way, I made a slight change to that area of the code, so it might have fixed the issue, could you pull the latest version and try it out?

**Comment by davidosomething** [comment]
Tried the latest -- here are some reproducible steps now:
1. New neovim
2. `:Bufferize messages`
3. `<C-w>j` to jump to the bufferized buffer
4. `:q`
5. `:Bufferize messages`

If I `:q` from the Bufferize buffer (both after step 2 and 5) and then `:ls`, the Bufferize buffer is still there btw

some maybe relevant settings I have

```
set hidden
set switchbuf=useopen
```

**Comment by AndrewRadev** [comment]
I thought it might be something related to hidden buffers, this is probably it. I'll see what I can do.

**Comment by AndrewRadev** [comment]
I've managed to reproduce it and I've pushed a potential fix. Could you try it out and let me know if it works?

**Comment by davidosomething** [comment]
works for me!
