### ISSUE TITLE
Bufferize buffer loses all content when hidden

### ISSUE THREAD

**Issue by mgedmin** [AndrewRadev/bufferize.vim#5]
Steps to reproduce:

- `:Bufferize scriptnames`
- pick any script, type `gf` to edit it
- use Ctrl-^ to go back to the Bufferize buffer

Expectation:

- I see all the script names

Reality:

- the buffer is empty

**Comment by mgedmin** [comment]
When I tried to reproduce this to make sure my instructions were correct, I got a different failure -- instead of an empty buffer I got an E86: Buffer 6 does not exist.  Nevertheless I could not return to where I wanted to return.

**Comment by AndrewRadev** [comment]
Bufferize creates a temporary buffer to hold the output of the command. The intention is for it to be a scratch buffer, not backed by any real file, like the quickfix or tree plugins' buffers. To that end, the buffer has a `set bufhidden=delete`, so that navigating away from it ends up deleting the buffer (this is generally the way Vim scratch buffers are supposed to be implemented).

That said, I can see how it'd make sense to keep the buffer around if you're using it for scriptnames, so you can go back from it. I've added an option that you can set:

``` vim
let g:bufferize_keep_buffers = 1
```

With this in your vimrc, the buffers will stay hidden when you navigate away from them. This might mean you end up with some leftover hidden buffers in your `:ls`, but it shouldn't be a practical problem. Multiple invocations of `Bufferize scriptnames` should also reuse the same buffer.

Could you check out the current master and see if it works for you? Does it fix your issue in a sensible way?

**Comment by mgedmin** [comment]
Thank you very much for adding that option!  It works perfectly.
